/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado.ahorcado;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import principal.Ventana;

/**
 *
 * @author Bryam
 */
public class Ahorcado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    AudioClip inicio,
            /**
             * Creates new form Ahorcado
             */
            audio1;
    Image icon;
    Juego game = new Juego();
    int play = 0, juegIn = 0;

    public Ahorcado() {
        initComponents();
        setTitle("CHILDREN'S GAME - AHORCADO");
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        setIconImage(new ImageIcon(getClass().getResource("/principal/logoM.png")).getImage());
        restaurar_color();
        this.getContentPane().setBackground(Color.WHITE);
        this.repaint();
        this.setLocationRelativeTo(null);
        bloque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        imagen_a = new javax.swing.JLabel();
        panelRound1 = new org.edisoncor.gui.panel.PanelRound();
        Palabra_oculta = new org.edisoncor.gui.textField.TextFieldRound();
        Error_Icon = new javax.swing.JLabel();
        panelRound2 = new org.edisoncor.gui.panel.PanelRound();
        button_A = new org.edisoncor.gui.button.ButtonNice();
        button_B = new org.edisoncor.gui.button.ButtonNice();
        button_C = new org.edisoncor.gui.button.ButtonNice();
        button_D = new org.edisoncor.gui.button.ButtonNice();
        button_E = new org.edisoncor.gui.button.ButtonNice();
        button_F = new org.edisoncor.gui.button.ButtonNice();
        button_G = new org.edisoncor.gui.button.ButtonNice();
        button_H = new org.edisoncor.gui.button.ButtonNice();
        button_I = new org.edisoncor.gui.button.ButtonNice();
        button_J = new org.edisoncor.gui.button.ButtonNice();
        button_O = new org.edisoncor.gui.button.ButtonNice();
        button_K = new org.edisoncor.gui.button.ButtonNice();
        button_L = new org.edisoncor.gui.button.ButtonNice();
        button_P = new org.edisoncor.gui.button.ButtonNice();
        button_Q = new org.edisoncor.gui.button.ButtonNice();
        button_M = new org.edisoncor.gui.button.ButtonNice();
        button_N = new org.edisoncor.gui.button.ButtonNice();
        button_R = new org.edisoncor.gui.button.ButtonNice();
        button_S = new org.edisoncor.gui.button.ButtonNice();
        button_Ñ = new org.edisoncor.gui.button.ButtonNice();
        button_T = new org.edisoncor.gui.button.ButtonNice();
        button_U = new org.edisoncor.gui.button.ButtonNice();
        button_V = new org.edisoncor.gui.button.ButtonNice();
        button_W = new org.edisoncor.gui.button.ButtonNice();
        button_X = new org.edisoncor.gui.button.ButtonNice();
        button_Y = new org.edisoncor.gui.button.ButtonNice();
        button_Z = new org.edisoncor.gui.button.ButtonNice();
        pist = new org.edisoncor.gui.button.ButtonIcon();
        controlM = new org.edisoncor.gui.button.ButtonIcon();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        jLabel2 = new javax.swing.JLabel();
        cant = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        detener = new javax.swing.JMenuItem();
        menPrin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnPlay = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel1.setColorPrimario(new java.awt.Color(0, 0, 102));
        panel1.setColorSecundario(new java.awt.Color(0, 255, 255));

        imagen_a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/ahorcado/imaAhorcado/0.png"))); // NOI18N

        panelRound1.setColorDeBorde(new java.awt.Color(51, 51, 51));
        panelRound1.setColorPrimario(new java.awt.Color(51, 153, 255));

        Palabra_oculta.setEditable(false);
        Palabra_oculta.setForeground(new java.awt.Color(204, 0, 0));
        Palabra_oculta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Palabra_oculta.setText("????????????");
        Palabra_oculta.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        Error_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/ahorcado/vidas/v8.png"))); // NOI18N

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(Error_Icon)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                        .addComponent(Palabra_oculta, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(Error_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Palabra_oculta, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelRound2.setColorDeBorde(new java.awt.Color(51, 51, 51));
        panelRound2.setColorPrimario(new java.awt.Color(0, 102, 255));

        button_A.setBackground(new java.awt.Color(0, 255, 0));
        button_A.setText("A");
        button_A.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_A.setSegundoColor(new java.awt.Color(0, 255, 204));
        button_A.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_A.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_AMouseMoved(evt);
            }
        });
        button_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AActionPerformed(evt);
            }
        });

        button_B.setText("B");
        button_B.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_B.setSegundoColor(new java.awt.Color(0, 255, 51));
        button_B.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_B.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_BMouseMoved(evt);
            }
        });
        button_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_BActionPerformed(evt);
            }
        });

        button_C.setBackground(new java.awt.Color(255, 0, 0));
        button_C.setText("C");
        button_C.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_C.setSegundoColor(new java.awt.Color(255, 255, 0));
        button_C.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_C.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_CMouseMoved(evt);
            }
        });
        button_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CActionPerformed(evt);
            }
        });

        button_D.setBackground(new java.awt.Color(255, 0, 204));
        button_D.setText("D");
        button_D.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_D.setSegundoColor(new java.awt.Color(255, 0, 0));
        button_D.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_D.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_DMouseMoved(evt);
            }
        });
        button_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DActionPerformed(evt);
            }
        });

        button_E.setBackground(new java.awt.Color(153, 153, 153));
        button_E.setText("E");
        button_E.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_E.setSegundoColor(new java.awt.Color(255, 0, 255));
        button_E.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_E.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_EMouseMoved(evt);
            }
        });
        button_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EActionPerformed(evt);
            }
        });

        button_F.setBackground(new java.awt.Color(255, 0, 0));
        button_F.setText("F");
        button_F.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_F.setSegundoColor(new java.awt.Color(255, 255, 0));
        button_F.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_F.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_FMouseMoved(evt);
            }
        });
        button_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FActionPerformed(evt);
            }
        });

        button_G.setBackground(new java.awt.Color(255, 0, 255));
        button_G.setText("G");
        button_G.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_G.setSegundoColor(new java.awt.Color(153, 153, 153));
        button_G.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_G.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_GMouseMoved(evt);
            }
        });
        button_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_GActionPerformed(evt);
            }
        });

        button_H.setBackground(new java.awt.Color(153, 153, 153));
        button_H.setText("H");
        button_H.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_H.setSegundoColor(new java.awt.Color(255, 0, 255));
        button_H.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_H.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_HMouseMoved(evt);
            }
        });
        button_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_HActionPerformed(evt);
            }
        });

        button_I.setText("I");
        button_I.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_I.setSegundoColor(new java.awt.Color(255, 0, 0));
        button_I.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_I.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_IMouseMoved(evt);
            }
        });
        button_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_IActionPerformed(evt);
            }
        });

        button_J.setBackground(new java.awt.Color(0, 255, 0));
        button_J.setText("J");
        button_J.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_J.setSegundoColor(new java.awt.Color(0, 255, 204));
        button_J.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_J.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_JMouseMoved(evt);
            }
        });
        button_J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_JActionPerformed(evt);
            }
        });

        button_O.setBackground(new java.awt.Color(255, 0, 0));
        button_O.setText("O");
        button_O.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_O.setSegundoColor(new java.awt.Color(255, 255, 0));
        button_O.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_O.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_OMouseMoved(evt);
            }
        });
        button_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_OActionPerformed(evt);
            }
        });

        button_K.setBackground(new java.awt.Color(102, 0, 102));
        button_K.setText("K");
        button_K.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_K.setSegundoColor(new java.awt.Color(0, 204, 0));
        button_K.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_K.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_KMouseMoved(evt);
            }
        });
        button_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_KActionPerformed(evt);
            }
        });

        button_L.setBackground(new java.awt.Color(0, 153, 153));
        button_L.setText("L");
        button_L.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_L.setSegundoColor(new java.awt.Color(204, 0, 0));
        button_L.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_L.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_LMouseMoved(evt);
            }
        });
        button_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LActionPerformed(evt);
            }
        });

        button_P.setBackground(new java.awt.Color(255, 0, 255));
        button_P.setText("P");
        button_P.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_P.setSegundoColor(new java.awt.Color(153, 153, 153));
        button_P.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_P.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_PMouseMoved(evt);
            }
        });
        button_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PActionPerformed(evt);
            }
        });

        button_Q.setBackground(new java.awt.Color(153, 153, 153));
        button_Q.setText("Q");
        button_Q.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_Q.setSegundoColor(new java.awt.Color(255, 0, 255));
        button_Q.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_Q.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_QMouseMoved(evt);
            }
        });
        button_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_QActionPerformed(evt);
            }
        });

        button_M.setBackground(new java.awt.Color(255, 0, 0));
        button_M.setText("M");
        button_M.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_M.setSegundoColor(new java.awt.Color(255, 255, 0));
        button_M.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_M.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_MMouseMoved(evt);
            }
        });
        button_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_MActionPerformed(evt);
            }
        });

        button_N.setBackground(new java.awt.Color(51, 102, 255));
        button_N.setText("N");
        button_N.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_N.setSegundoColor(new java.awt.Color(255, 255, 0));
        button_N.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_N.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_NMouseMoved(evt);
            }
        });
        button_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_NActionPerformed(evt);
            }
        });

        button_R.setText("R");
        button_R.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_R.setSegundoColor(new java.awt.Color(255, 0, 0));
        button_R.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_R.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_RMouseMoved(evt);
            }
        });
        button_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_RActionPerformed(evt);
            }
        });

        button_S.setBackground(new java.awt.Color(0, 255, 0));
        button_S.setText("S");
        button_S.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_S.setSegundoColor(new java.awt.Color(0, 255, 204));
        button_S.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_S.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_SMouseMoved(evt);
            }
        });
        button_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SActionPerformed(evt);
            }
        });

        button_Ñ.setBackground(new java.awt.Color(153, 51, 0));
        button_Ñ.setText("Ñ");
        button_Ñ.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_Ñ.setSegundoColor(new java.awt.Color(0, 153, 0));
        button_Ñ.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_Ñ.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_ÑMouseMoved(evt);
            }
        });
        button_Ñ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ÑActionPerformed(evt);
            }
        });

        button_T.setBackground(new java.awt.Color(51, 0, 153));
        button_T.setText("T");
        button_T.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_T.setSegundoColor(new java.awt.Color(255, 102, 255));
        button_T.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_T.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_TMouseMoved(evt);
            }
        });
        button_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TActionPerformed(evt);
            }
        });

        button_U.setBackground(new java.awt.Color(0, 102, 0));
        button_U.setText("U");
        button_U.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_U.setSegundoColor(new java.awt.Color(102, 0, 102));
        button_U.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_U.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_UMouseMoved(evt);
            }
        });
        button_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UActionPerformed(evt);
            }
        });

        button_V.setBackground(new java.awt.Color(0, 153, 153));
        button_V.setText("V");
        button_V.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_V.setSegundoColor(new java.awt.Color(0, 0, 153));
        button_V.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_V.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_VMouseMoved(evt);
            }
        });
        button_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_VActionPerformed(evt);
            }
        });

        button_W.setBackground(new java.awt.Color(153, 153, 0));
        button_W.setText("W");
        button_W.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_W.setSegundoColor(new java.awt.Color(0, 0, 153));
        button_W.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_W.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_WMouseMoved(evt);
            }
        });
        button_W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_WActionPerformed(evt);
            }
        });

        button_X.setBackground(new java.awt.Color(255, 255, 255));
        button_X.setText("X");
        button_X.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_X.setSegundoColor(new java.awt.Color(204, 204, 0));
        button_X.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_X.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_XMouseMoved(evt);
            }
        });
        button_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_XActionPerformed(evt);
            }
        });

        button_Y.setBackground(new java.awt.Color(102, 0, 102));
        button_Y.setText("Y");
        button_Y.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_Y.setSegundoColor(new java.awt.Color(0, 0, 153));
        button_Y.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_Y.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_YMouseMoved(evt);
            }
        });
        button_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_YActionPerformed(evt);
            }
        });

        button_Z.setBackground(new java.awt.Color(153, 0, 0));
        button_Z.setText("Z");
        button_Z.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        button_Z.setSegundoColor(new java.awt.Color(102, 0, 102));
        button_Z.setSegundoColorDeTexto(new java.awt.Color(0, 0, 0));
        button_Z.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                button_ZMouseMoved(evt);
            }
        });
        button_Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ZActionPerformed(evt);
            }
        });

        pist.setBackground(new java.awt.Color(0, 204, 255));
        pist.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/ahorcado/pista.png"))); // NOI18N
        pist.setText("buttonIcon1");
        pist.setToolTipText("Pista");
        pist.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pistMouseMoved(evt);
            }
        });
        pist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pistActionPerformed(evt);
            }
        });

        controlM.setBackground(new java.awt.Color(0, 204, 0));
        controlM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        controlM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/mas/play.png"))); // NOI18N
        controlM.setText("buttonIcon1");
        controlM.setToolTipText("Iniciar");
        controlM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                controlMMouseMoved(evt);
            }
        });
        controlM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controlMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(button_M, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_N, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_Ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_O, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_P, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(button_G, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_H, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_I, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_J, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_K, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_L, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(button_A, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_B, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_D, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_E, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_F, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(button_R, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_S, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_T, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_U, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(button_X, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(button_V, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button_W, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRound2Layout.createSequentialGroup()
                                .addComponent(pist, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(controlM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addGap(68, 68, 68))
        );

        panelRound2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button_A, button_B, button_C, button_D, button_E});

        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_J, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_K, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Ñ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_O, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Q, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_U, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_W, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_Z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(pist, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addComponent(controlM, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelRound2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button_A, button_B, button_C, button_D, button_E});

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/logoM.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        labelMetric1.setText("¡¡¡ Encuentra La Palabra Oculta !!!");
        labelMetric1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de Letras:");

        cant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cant.setForeground(new java.awt.Color(255, 255, 255));
        cant.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagen_a)
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelCurves1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCurves1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCurves1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                                        .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))))
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCurves1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagen_a))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                        .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCurves1Layout.createSequentialGroup()
                                .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelCurves1Layout.createSequentialGroup()
                                .addComponent(labelMetric1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/ahorcado/inicio.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        nuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/ahorcado/nuevo.png"))); // NOI18N
        nuevo.setText("Nuevo Juego");
        nuevo.setToolTipText("");
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevo);

        detener.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detener.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/ahorcado/det.png"))); // NOI18N
        detener.setText("Detener Juego");
        detener.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerActionPerformed(evt);
            }
        });
        jMenu1.add(detener);

        menPrin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/mas/inicio2.png"))); // NOI18N
        menPrin.setText("Menú Principal");
        menPrin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menPrinActionPerformed(evt);
            }
        });
        jMenu1.add(menPrin);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/mas/mas.png"))); // NOI18N
        jMenu2.setText("Más");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnPlay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/mas/play1.png"))); // NOI18N
        btnPlay.setText("Iniciar Musica");
        btnPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        jMenu2.add(btnPlay);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/mas/in.png"))); // NOI18N
        jMenuItem1.setText("Información del juego");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        play = 1;
        juegIn = 1;
        btnPlay.setEnabled(true);
        btnPlay.setText("Detener Musica");
        btnPlay.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/stop1.png")));
        controlM.setEnabled(true);
        controlM.setBackground(Color.red);
        controlM.setToolTipText("Detener");
        controlM.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/stop.png")));
        game = new Juego(Palabra_oculta, Error_Icon, imagen_a);
        cant.setText(game.can);
        nuevo.setEnabled(false);
        detener.setEnabled(true);
        restaurar_color();
    }//GEN-LAST:event_nuevoActionPerformed

    private void detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        if (play == 1) {
            btnPlay.setText("Iniciar Musica");
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/play1.png")));
            controlM.setBackground(Color.green);
            controlM.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/play.png")));
            game.inicio.stop();
            play = 0;
        } else {
            btnPlay.setText("Iniciar Musica");
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/play1.png")));
            controlM.setBackground(Color.green);
            controlM.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/play.png")));
        }
        bloque();
        cant.setText("");
        Palabra_oculta.setText("????????????");
        Error_Icon.setIcon(new ImageIcon(getClass().getResource("/ahorcado/ahorcado/vidas/v8.png")));
        nuevo.setEnabled(true);
        detener.setEnabled(false);
        JOptionPane.showMessageDialog(null, "        ¡ Juego Detenido !\nPuedes Empezar un Nuevo Juego", "Detener", JOptionPane.ERROR_MESSAGE);
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
    }//GEN-LAST:event_detenerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        JOptionPane.showMessageDialog(null, "Este juego consiste en encontrar la palabra que esta oculta an-\n"
                + "tes de que terminen tus intentos, se cuenta con 8 intentos al\n"
                + "empezar a jugar, los cuales se van descontando por cada letra\n"
                + "incorrecta que presiones.\n\n"
                + "                                       ¡¡¡ OJO !!!\n"
                + "Al iniciar el juego se te da una pista, si se te olvida solo\n"
                + "presionas el boton que tiene una huella y ahi te da la pista.\n\n"
                + "El juego cuenta con 142 palabras diferentes que te pueden salir\n"
                + "de forma aleatoria.\n"
                + "\n"
                + "El objetivo es encontrar la palabra antes de terminar tus in-\n"
                + "tentos para salvar al hombrecito.", "Información", JOptionPane.INFORMATION_MESSAGE);
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void button_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('A');
        button_A.setText(" ");
        button_A.setBackground(Color.black);
        button_A.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_AActionPerformed

    private void button_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_BActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('B');
        button_B.setText(" ");
        button_B.setBackground(Color.black);
        button_B.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_BActionPerformed

    private void button_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('C');
        button_C.setText(" ");
        button_C.setBackground(Color.black);
        button_C.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_CActionPerformed

    private void button_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('D');
        button_D.setText(" ");
        button_D.setBackground(Color.black);
        button_D.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_DActionPerformed

    private void button_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('E');
        button_E.setText(" ");
        button_E.setBackground(Color.black);
        button_E.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_EActionPerformed

    private void button_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('F');
        button_F.setText(" ");
        button_F.setBackground(Color.black);
        button_F.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_FActionPerformed

    private void button_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_GActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('G');
        button_G.setText(" ");
        button_G.setBackground(Color.black);
        button_G.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_GActionPerformed

    private void button_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_HActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('H');
        button_H.setText(" ");
        button_H.setBackground(Color.black);
        button_H.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_HActionPerformed

    private void button_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_IActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('I');
        button_I.setText(" ");
        button_I.setBackground(Color.black);
        button_I.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_IActionPerformed

    private void button_JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_JActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('J');
        button_J.setText(" ");
        button_J.setBackground(Color.black);
        button_J.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_JActionPerformed

    private void button_KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_KActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('K');
        button_K.setText(" ");
        button_K.setBackground(Color.black);
        button_K.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_KActionPerformed

    private void button_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('L');
        button_L.setText(" ");
        button_L.setBackground(Color.black);
        button_L.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_LActionPerformed

    private void button_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_MActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('M');
        button_M.setText(" ");
        button_M.setBackground(Color.black);
        button_M.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_MActionPerformed

    private void button_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_NActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('N');
        button_N.setText(" ");
        button_N.setBackground(Color.black);
        button_N.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_NActionPerformed

    private void button_ÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ÑActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('Ñ');
        button_Ñ.setText(" ");
        button_Ñ.setBackground(Color.black);
        button_Ñ.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_ÑActionPerformed

    private void button_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_OActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('O');
        button_O.setText(" ");
        button_O.setBackground(Color.black);
        button_O.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_OActionPerformed

    private void button_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('P');
        button_P.setText(" ");
        button_P.setBackground(Color.black);
        button_P.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_PActionPerformed

    private void button_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_QActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('Q');
        button_Q.setText(" ");
        button_Q.setBackground(Color.black);
        button_Q.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_QActionPerformed

    private void button_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_RActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('R');
        button_R.setText(" ");
        button_R.setBackground(Color.black);
        button_R.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_RActionPerformed

    private void button_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('S');
        button_S.setText(" ");
        button_S.setBackground(Color.black);
        button_S.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_SActionPerformed

    private void button_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('T');
        button_T.setText(" ");
        button_T.setBackground(Color.black);
        button_T.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_TActionPerformed

    private void button_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('U');
        button_U.setText(" ");
        button_U.setBackground(Color.black);
        button_U.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_UActionPerformed

    private void button_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_VActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('V');
        button_V.setText(" ");
        button_V.setBackground(Color.black);
        button_V.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_VActionPerformed

    private void button_WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_WActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('W');
        button_W.setText(" ");
        button_W.setBackground(Color.black);
        button_W.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_WActionPerformed

    private void button_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_XActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('X');
        button_X.setText(" ");
        button_X.setBackground(Color.black);
        button_X.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_XActionPerformed

    private void button_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_YActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('Y');
        button_Y.setText(" ");
        button_Y.setBackground(Color.black);
        button_Y.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_YActionPerformed

    private void button_ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ZActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        game.evaluar('Z');
        button_Z.setText(" ");
        button_Z.setBackground(Color.black);
        button_Z.setEnabled(false);
        if (game.intentos == 8) {
            juegIn = 0;
            bloque();
        }
        if (game.win == true) {
            juegIn = 0;
            bloque();
        }
    }//GEN-LAST:event_button_ZActionPerformed

    private void button_AMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AMouseMoved
        button_A.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_AMouseMoved

    private void button_BMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_BMouseMoved
        button_B.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_BMouseMoved

    private void button_CMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_CMouseMoved
        button_C.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_CMouseMoved

    private void button_DMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DMouseMoved
        button_D.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_DMouseMoved

    private void button_EMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_EMouseMoved
        button_E.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_EMouseMoved

    private void button_FMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_FMouseMoved
        button_F.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_FMouseMoved

    private void button_GMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_GMouseMoved
        button_G.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_GMouseMoved

    private void button_HMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_HMouseMoved
        button_H.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_HMouseMoved

    private void button_IMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_IMouseMoved
        button_I.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_IMouseMoved

    private void button_JMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_JMouseMoved
        button_J.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_JMouseMoved

    private void button_KMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_KMouseMoved
        button_K.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_KMouseMoved

    private void button_LMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_LMouseMoved
        button_L.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_LMouseMoved

    private void button_MMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_MMouseMoved
        button_M.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_MMouseMoved

    private void button_NMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_NMouseMoved
        button_N.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_NMouseMoved

    private void button_ÑMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ÑMouseMoved
        button_Ñ.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_ÑMouseMoved

    private void button_OMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_OMouseMoved
        button_O.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_OMouseMoved

    private void button_PMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_PMouseMoved
        button_P.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_PMouseMoved

    private void button_QMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_QMouseMoved
        button_Q.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_QMouseMoved

    private void button_RMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_RMouseMoved
        button_R.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_RMouseMoved

    private void button_SMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SMouseMoved
        button_S.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_SMouseMoved

    private void button_TMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_TMouseMoved
        button_T.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_TMouseMoved

    private void button_UMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_UMouseMoved
        button_U.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_UMouseMoved

    private void button_VMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_VMouseMoved
        button_V.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_VMouseMoved

    private void button_WMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_WMouseMoved
        button_W.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_WMouseMoved

    private void button_XMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_XMouseMoved
        button_X.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_XMouseMoved

    private void button_YMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_YMouseMoved
        button_Y.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_YMouseMoved

    private void button_ZMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ZMouseMoved
        button_Z.setCursor(new Cursor(12));
    }//GEN-LAST:event_button_ZMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        audio1.play();
        close();
    }//GEN-LAST:event_formWindowClosing

    private void pistMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pistMouseMoved
        pist.setCursor(new Cursor(12));
    }//GEN-LAST:event_pistMouseMoved

    private void pistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pistActionPerformed
        audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        audio1.play();
        JOptionPane.showMessageDialog(null, game.pistaP, "Ahorcado",
                0, new javax.swing.ImageIcon(getClass().getResource("/ahorcado/ahorcado/pista.png")));
        audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        audio1.play();
    }//GEN-LAST:event_pistActionPerformed

    private void controlMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlMMouseMoved
        controlM.setCursor(new Cursor(12));
    }//GEN-LAST:event_controlMMouseMoved

    private void controlMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controlMActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        if (play == 1) {
            btnPlay.setText("Iniciar Musica");
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/play1.png")));
            controlM.setBackground(Color.green);
            controlM.setToolTipText("Iniciar");
            controlM.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/play.png")));
            game.inicio.stop();
            play = 0;
        } else {
            btnPlay.setText("Detener Musica");
            btnPlay.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/stop1.png")));
            controlM.setBackground(Color.red);
            controlM.setToolTipText("Detener");
            controlM.setIcon(new ImageIcon(getClass().getResource("/ahorcado/mas/stop.png")));
            game.inicio.play();
            play = 1;
        }
    }//GEN-LAST:event_controlMActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        controlMActionPerformed(evt);
    }//GEN-LAST:event_btnPlayActionPerformed

    private void menPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menPrinActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
        inicio.play();
        if (juegIn == 1) {
            int seleccion = JOptionPane.showConfirmDialog(null, "   Se perdera la partida\nsi regresa al menú principal\n"
                    + "\n     ¿Desea continuar?",
                    "Ahorcado",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    new javax.swing.ImageIcon(getClass().getResource("/ahorcado/mas/inicio1.png")));
            inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
            inicio.play();

            if (seleccion == 0) {
                game.inicio.stop();
                this.dispose();
                new Ventana().setVisible(true);
            }
        } else {
            int seleccion = JOptionPane.showConfirmDialog(null, "¿Regresar al menú principal?",
                    "Ahorcado",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                    new javax.swing.ImageIcon(getClass().getResource("/ahorcado/mas/inicio1.png")));
            inicio = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
            inicio.play();
//            Juego j = new Juego();
//            j.inicio.stop();
            if (seleccion == 0) {
                this.dispose();
                new Ventana().setVisible(true);
            }
        }

    }//GEN-LAST:event_menPrinActionPerformed
    private void close() {
        if (JOptionPane.showConfirmDialog(rootPane, "¿Salir de la aplicación?",
                "Ahorcado", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE) == JOptionPane.YES_OPTION) {
            audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
            audio1.play();
            System.exit(0);
        } else {
            audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
            audio1.play();
            setDefaultCloseOperation(0);
        }
    }

    public void bloque() {

        controlM.setEnabled(false);
        btnPlay.setEnabled(false);
        pist.setEnabled(false);
        nuevo.setEnabled(true);
        detener.setEnabled(false);
        button_A.setText(" ");
        button_A.setBackground(Color.black);
        button_A.setEnabled(false);
        button_B.setText(" ");
        button_B.setBackground(Color.black);
        button_B.setEnabled(false);
        button_D.setEnabled(false);
        button_D.setText(" ");
        button_D.setBackground(Color.black);
        button_C.setEnabled(false);
        button_C.setText(" ");
        button_C.setBackground(Color.black);
        button_E.setEnabled(false);
        button_E.setText(" ");
        button_E.setBackground(Color.black);
        button_F.setEnabled(false);
        button_F.setText(" ");
        button_F.setBackground(Color.black);
        button_G.setEnabled(false);
        button_G.setText(" ");
        button_G.setBackground(Color.black);
        button_H.setEnabled(false);
        button_H.setText(" ");
        button_H.setBackground(Color.black);
        button_I.setEnabled(false);
        button_I.setText(" ");
        button_I.setBackground(Color.black);
        button_J.setEnabled(false);
        button_J.setText(" ");
        button_J.setBackground(Color.black);
        button_K.setEnabled(false);
        button_K.setText(" ");
        button_K.setBackground(Color.black);
        button_L.setEnabled(false);
        button_L.setText(" ");
        button_L.setBackground(Color.black);
        button_M.setEnabled(false);
        button_M.setText(" ");
        button_M.setBackground(Color.black);
        button_N.setEnabled(false);
        button_N.setText(" ");
        button_N.setBackground(Color.black);
        button_Ñ.setEnabled(false);
        button_Ñ.setText(" ");
        button_Ñ.setBackground(Color.black);
        button_O.setEnabled(false);
        button_O.setText(" ");
        button_O.setBackground(Color.black);
        button_P.setEnabled(false);
        button_P.setText(" ");
        button_P.setBackground(Color.black);
        button_Q.setEnabled(false);
        button_Q.setText(" ");
        button_Q.setBackground(Color.black);
        button_R.setEnabled(false);
        button_R.setText(" ");
        button_R.setBackground(Color.black);
        button_S.setEnabled(false);
        button_S.setText(" ");
        button_S.setBackground(Color.black);
        button_T.setEnabled(false);
        button_T.setText(" ");
        button_T.setBackground(Color.black);
        button_U.setEnabled(false);
        button_U.setText(" ");
        button_U.setBackground(Color.black);
        button_V.setEnabled(false);
        button_V.setText(" ");
        button_V.setBackground(Color.black);
        button_W.setEnabled(false);
        button_W.setText(" ");
        button_W.setBackground(Color.black);
        button_X.setEnabled(false);
        button_X.setText(" ");
        button_X.setBackground(Color.black);
        button_Y.setEnabled(false);
        button_Y.setText(" ");
        button_Y.setBackground(Color.black);
        button_Z.setEnabled(false);
        button_Z.setText(" ");
        button_Z.setBackground(Color.black);
    }

    public void restaurar_color() {
        pist.setEnabled(true);
        button_A.setEnabled(true);
        button_A.setText("A");
        button_A.setBackground(Color.green);
        button_B.setEnabled(true);
        button_B.setText("B");
        button_B.setBackground(Color.yellow);
        button_D.setEnabled(true);
        button_D.setText("D");
        button_D.setBackground(Color.magenta);
        button_C.setEnabled(true);
        button_C.setText("C");
        button_C.setBackground(Color.red);
        button_E.setEnabled(true);
        button_E.setText("E");
        button_E.setBackground(Color.darkGray);
        button_F.setEnabled(true);
        button_F.setText("F");
        button_F.setBackground(Color.red);
        button_G.setEnabled(true);
        button_G.setText("G");
        button_G.setBackground(Color.magenta);
        button_H.setEnabled(true);
        button_H.setText("H");
        button_H.setBackground(Color.darkGray);
        button_I.setEnabled(true);
        button_I.setText("I");
        button_I.setBackground(Color.yellow);
        button_J.setEnabled(true);
        button_J.setText("J");
        button_J.setBackground(Color.green);
        button_K.setEnabled(true);
        button_K.setText("K");
        button_K.setBackground(Color.cyan);
        button_L.setEnabled(true);
        button_L.setText("L");
        button_L.setBackground(Color.blue);
        button_M.setEnabled(true);
        button_M.setText("M");
        button_M.setBackground(Color.RED);
        button_N.setEnabled(true);
        button_N.setText("N");
        button_N.setBackground(Color.CYAN);
        button_Ñ.setEnabled(true);
        button_Ñ.setText("Ñ");
        button_Ñ.setBackground(Color.PINK);
        button_O.setEnabled(true);
        button_O.setText("O");
        button_O.setBackground(Color.MAGENTA);
        button_P.setEnabled(true);
        button_P.setText("P");
        button_P.setBackground(Color.GREEN);
        button_Q.setEnabled(true);
        button_Q.setText("Q");
        button_Q.setBackground(Color.YELLOW);
        button_R.setEnabled(true);
        button_R.setText("R");
        button_R.setBackground(Color.DARK_GRAY);
        button_S.setEnabled(true);
        button_S.setText("S");
        button_S.setBackground(Color.GREEN);
        button_T.setEnabled(true);
        button_T.setText("T");
        button_T.setBackground(Color.CYAN);
        button_U.setEnabled(true);
        button_U.setText("U");
        button_U.setBackground(Color.BLUE);
        button_V.setEnabled(true);
        button_V.setText("V");
        button_V.setBackground(Color.YELLOW);
        button_W.setEnabled(true);
        button_W.setText("W");
        button_W.setBackground(Color.CYAN);
        button_X.setEnabled(true);
        button_X.setText("X");
        button_X.setBackground(Color.RED);
        button_Y.setEnabled(true);
        button_Y.setText("Y");
        button_Y.setBackground(Color.MAGENTA);
        button_Z.setEnabled(true);
        button_Z.setText("Z");
        button_Z.setBackground(Color.YELLOW);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error_Icon;
    private org.edisoncor.gui.textField.TextFieldRound Palabra_oculta;
    private javax.swing.JMenuItem btnPlay;
    private org.edisoncor.gui.button.ButtonNice button_A;
    private org.edisoncor.gui.button.ButtonNice button_B;
    private org.edisoncor.gui.button.ButtonNice button_C;
    private org.edisoncor.gui.button.ButtonNice button_D;
    private org.edisoncor.gui.button.ButtonNice button_E;
    private org.edisoncor.gui.button.ButtonNice button_F;
    private org.edisoncor.gui.button.ButtonNice button_G;
    private org.edisoncor.gui.button.ButtonNice button_H;
    private org.edisoncor.gui.button.ButtonNice button_I;
    private org.edisoncor.gui.button.ButtonNice button_J;
    private org.edisoncor.gui.button.ButtonNice button_K;
    private org.edisoncor.gui.button.ButtonNice button_L;
    private org.edisoncor.gui.button.ButtonNice button_M;
    private org.edisoncor.gui.button.ButtonNice button_N;
    private org.edisoncor.gui.button.ButtonNice button_O;
    private org.edisoncor.gui.button.ButtonNice button_P;
    private org.edisoncor.gui.button.ButtonNice button_Q;
    private org.edisoncor.gui.button.ButtonNice button_R;
    private org.edisoncor.gui.button.ButtonNice button_S;
    private org.edisoncor.gui.button.ButtonNice button_T;
    private org.edisoncor.gui.button.ButtonNice button_U;
    private org.edisoncor.gui.button.ButtonNice button_V;
    private org.edisoncor.gui.button.ButtonNice button_W;
    private org.edisoncor.gui.button.ButtonNice button_X;
    private org.edisoncor.gui.button.ButtonNice button_Y;
    private org.edisoncor.gui.button.ButtonNice button_Z;
    private org.edisoncor.gui.button.ButtonNice button_Ñ;
    public javax.swing.JLabel cant;
    private org.edisoncor.gui.button.ButtonIcon controlM;
    private javax.swing.JMenuItem detener;
    public javax.swing.JLabel imagen_a;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private javax.swing.JMenuItem menPrin;
    public javax.swing.JMenuItem nuevo;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelRound panelRound1;
    private org.edisoncor.gui.panel.PanelRound panelRound2;
    private org.edisoncor.gui.button.ButtonIcon pist;
    // End of variables declaration//GEN-END:variables
}
