/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import alfabeto.Alfabeto;
import gato.Jugadores;
import gato.Tablero;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import matematicas.inicioMat;
import org.edisoncor.gui.util.Avatar;

/**
 *
 * @author Bryam
 */
public class Ventana extends javax.swing.JFrame {

    AudioClip audio, audio1;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        setSize(1100, 600);
        setLocationRelativeTo(null);
//        setResizable(false);
        setTitle("CHILDREN'S GAME - MENÚ PRINCIPAL");
        setIconImage(new ImageIcon(getClass().getResource("/principal/logoM.png")).getImage());
        llenarMenu();
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }

    public void llenarMenu() {
        java.util.List<Avatar> avatars = new ArrayList<Avatar>();
        avatars.add(new Avatar("Rompecabezas", loadImage("/principal/imagenes/rom.png")));
        avatars.add(new Avatar("Pares", loadImage("/principal/imagenes/par.png")));
        avatars.add(new Avatar("Tres en Raya", loadImage("/principal/imagenes/gat.png")));
        avatars.add(new Avatar("Ahorcado", loadImage("/principal/imagenes/ahor.png")));
        avatars.add(new Avatar("Matemáticas", loadImage("/principal/imagenes/mat.png")));
        avatars.add(new Avatar("Alfabeto", loadImage("/principal/imagenes/alf.png")));
        avatars.add(new Avatar("Salir", loadImage("/principal/imagenes/salir.png")));
        av.setAvatars(avatars);
    }

    public static Image loadImage(String fileName) {
        try {
            return ImageIO.read(Ventana.class.getResource(fileName));
        } catch (Exception e) {
            return null;
        }
    }

    public void llamarMenu() {
        if (av.getSelectedtitulo().equals("Rompecabezas")) {
            this.dispose();
            new rompecabezas.rompecabezas.InicioR().setVisible(true);
        }
        if (av.getSelectedtitulo().equals("Pares")) {
            this.dispose();
            new pares.pares.InicioP().setVisible(true);
        }
        if (av.getSelectedtitulo().equals("Tres en Raya")) {
            this.dispose();
            new gato.Jugadores().setVisible(true);
        }
        if (av.getSelectedtitulo().equals("Ahorcado")) {
            this.dispose();
            new ahorcado.ahorcado.Ahorcado().setVisible(true);
        }
        if (av.getSelectedtitulo().equals("Matemáticas")) {
            this.dispose();
            new matematicas.inicioMat().setVisible(true);
        }
        if (av.getSelectedtitulo().equals("Alfabeto")) {
            this.dispose();
            new alfabeto.Alfabeto().setVisible(true);
        }
        if (av.getSelectedtitulo().equals("Salir")) {
            close();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        av = new org.edisoncor.gui.panel.PanelAvatarChooser();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        titulo = new org.edisoncor.gui.label.LabelTask();
        ac = new org.edisoncor.gui.button.ButtonIpod();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        av.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/imag/fondo2.png"))); // NOI18N
        av.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                avKeyPressed(evt);
            }
        });

        panelCurves1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/logoM.png"))); // NOI18N
        titulo.setText("¡¡¡ BIENVENIDOS A CHILDREN'S GAME !!!");
        titulo.setCategoryFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titulo.setCategorySmallFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        titulo.setColorDeBorde(new java.awt.Color(255, 255, 255));
        titulo.setDescription("JUEGO INFANTIL");
        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        ac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ac.setText(".");
        ac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout avLayout = new javax.swing.GroupLayout(av);
        av.setLayout(avLayout);
        avLayout.setHorizontalGroup(
            avLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(avLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                    .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
            .addGroup(avLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(avLayout.createSequentialGroup()
                    .addContainerGap(317, Short.MAX_VALUE)
                    .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );
        avLayout.setVerticalGroup(
            avLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avLayout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(panelCurves1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(avLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(avLayout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(70, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(av, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(av, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acMouseClicked
        audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/principal/2.mp3"));
        audio1.play();
        llamarMenu();
    }//GEN-LAST:event_acMouseClicked

    private void avKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_avKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/principal/2.mp3"));
            audio1.play();
            llamarMenu();
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_RIGHT || evt.getKeyCode() == KeyEvent.VK_LEFT || evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
                audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/principal/2.mp3"));
                audio1.play();
            } else {
                Toolkit.getDefaultToolkit().beep();
            }

        }
    }//GEN-LAST:event_avKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/principal/2.mp3"));
        audio1.play();
        close();
    }//GEN-LAST:event_formWindowClosing
    private void close() {
        if (JOptionPane.showConfirmDialog(rootPane, "¿Salir de la aplicación?",
                "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE) == JOptionPane.YES_OPTION) {
            audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/principal/2.mp3"));
            audio1.play();
            System.exit(0);
        } else {
            audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/principal/2.mp3"));
            audio1.play();
            setDefaultCloseOperation(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIpod ac;
    private org.edisoncor.gui.panel.PanelAvatarChooser av;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.label.LabelTask titulo;
    // End of variables declaration//GEN-END:variables
}
