/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alfabeto;

import java.applet.AudioClip;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import principal.Ventana;

/**
 *
 * @author Bryam
 */
public class Alfabeto extends javax.swing.JFrame {

    AudioClip audio, audio1, inicio;

    /**
     * Creates new form Alfabeto
     */
    public Alfabeto() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/principal/logoM.png")).getImage());
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(785, 580);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        panelCurves2 = new org.edisoncor.gui.panel.PanelCurves();
        panel4 = new org.edisoncor.gui.panel.Panel();
        jLabel2 = new javax.swing.JLabel();
        button_A1 = new javax.swing.JButton();
        button_J1 = new javax.swing.JButton();
        button_R1 = new javax.swing.JButton();
        button_S1 = new javax.swing.JButton();
        button_K1 = new javax.swing.JButton();
        button_B1 = new javax.swing.JButton();
        button_C1 = new javax.swing.JButton();
        button_D1 = new javax.swing.JButton();
        button_M1 = new javax.swing.JButton();
        button_L1 = new javax.swing.JButton();
        button_T1 = new javax.swing.JButton();
        button_U1 = new javax.swing.JButton();
        button_V1 = new javax.swing.JButton();
        button_W1 = new javax.swing.JButton();
        button_Ñ1 = new javax.swing.JButton();
        button_N1 = new javax.swing.JButton();
        button_E1 = new javax.swing.JButton();
        button_F1 = new javax.swing.JButton();
        button_G1 = new javax.swing.JButton();
        button_H1 = new javax.swing.JButton();
        button_I1 = new javax.swing.JButton();
        button_Q1 = new javax.swing.JButton();
        button_P1 = new javax.swing.JButton();
        button_O1 = new javax.swing.JButton();
        button_X1 = new javax.swing.JButton();
        button_Y1 = new javax.swing.JButton();
        button_Z1 = new javax.swing.JButton();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel3 = new javax.swing.JLabel();
        panel3 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        button_A = new javax.swing.JButton();
        button_J = new javax.swing.JButton();
        button_R = new javax.swing.JButton();
        button_S = new javax.swing.JButton();
        button_K = new javax.swing.JButton();
        button_B = new javax.swing.JButton();
        button_C = new javax.swing.JButton();
        button_L = new javax.swing.JButton();
        button_T = new javax.swing.JButton();
        button_U = new javax.swing.JButton();
        button_M = new javax.swing.JButton();
        button_D = new javax.swing.JButton();
        button_E = new javax.swing.JButton();
        button_N = new javax.swing.JButton();
        button_V = new javax.swing.JButton();
        button_W = new javax.swing.JButton();
        button_Ñ = new javax.swing.JButton();
        button_F = new javax.swing.JButton();
        button_G = new javax.swing.JButton();
        button_O = new javax.swing.JButton();
        button_X = new javax.swing.JButton();
        button_Y = new javax.swing.JButton();
        button_P = new javax.swing.JButton();
        button_H = new javax.swing.JButton();
        button_I = new javax.swing.JButton();
        button_Q = new javax.swing.JButton();
        button_Z = new javax.swing.JButton();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel1.setColorPrimario(new java.awt.Color(255, 153, 204));

        panel2.setColorPrimario(new java.awt.Color(51, 51, 255));

        panel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel4.setColorPrimario(new java.awt.Color(102, 204, 255));
        panel4.setColorSecundario(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfabeto/pala.gif"))); // NOI18N

        button_A1.setBackground(new java.awt.Color(255, 153, 255));
        button_A1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_A1.setText("Aa");
        button_A1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_A1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_A1MousePressed(evt);
            }
        });

        button_J1.setBackground(new java.awt.Color(255, 153, 255));
        button_J1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_J1.setText("Jj");
        button_J1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_J1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_J1MousePressed(evt);
            }
        });

        button_R1.setBackground(new java.awt.Color(255, 153, 255));
        button_R1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_R1.setText("Rr");
        button_R1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_R1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_R1MousePressed(evt);
            }
        });

        button_S1.setBackground(new java.awt.Color(255, 153, 255));
        button_S1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_S1.setText("Ss");
        button_S1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_S1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_S1MousePressed(evt);
            }
        });

        button_K1.setBackground(new java.awt.Color(255, 153, 255));
        button_K1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_K1.setText("Kk");
        button_K1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_K1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_K1MousePressed(evt);
            }
        });

        button_B1.setBackground(new java.awt.Color(255, 153, 255));
        button_B1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_B1.setText("Bb");
        button_B1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_B1MousePressed(evt);
            }
        });

        button_C1.setBackground(new java.awt.Color(255, 153, 255));
        button_C1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_C1.setText("Cc");
        button_C1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_C1MousePressed(evt);
            }
        });

        button_D1.setBackground(new java.awt.Color(255, 153, 255));
        button_D1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_D1.setText("Dd");
        button_D1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_D1MousePressed(evt);
            }
        });

        button_M1.setBackground(new java.awt.Color(255, 153, 255));
        button_M1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_M1.setText("Mm");
        button_M1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_M1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_M1MousePressed(evt);
            }
        });

        button_L1.setBackground(new java.awt.Color(255, 153, 255));
        button_L1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_L1.setText("Ll");
        button_L1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_L1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_L1MousePressed(evt);
            }
        });

        button_T1.setBackground(new java.awt.Color(255, 153, 255));
        button_T1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_T1.setText("Tt");
        button_T1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_T1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_T1MousePressed(evt);
            }
        });

        button_U1.setBackground(new java.awt.Color(255, 153, 255));
        button_U1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_U1.setText("Uu");
        button_U1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_U1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_U1MousePressed(evt);
            }
        });

        button_V1.setBackground(new java.awt.Color(255, 153, 255));
        button_V1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_V1.setText("Vv");
        button_V1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_V1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_V1MousePressed(evt);
            }
        });

        button_W1.setBackground(new java.awt.Color(255, 153, 255));
        button_W1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_W1.setText("Ww");
        button_W1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_W1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_W1MousePressed(evt);
            }
        });

        button_Ñ1.setBackground(new java.awt.Color(255, 153, 255));
        button_Ñ1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Ñ1.setText("Ññ");
        button_Ñ1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Ñ1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_Ñ1MousePressed(evt);
            }
        });

        button_N1.setBackground(new java.awt.Color(255, 153, 255));
        button_N1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_N1.setText("Nn");
        button_N1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_N1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_N1MousePressed(evt);
            }
        });

        button_E1.setBackground(new java.awt.Color(255, 153, 255));
        button_E1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_E1.setText("Ee");
        button_E1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_E1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_E1MousePressed(evt);
            }
        });

        button_F1.setBackground(new java.awt.Color(255, 153, 255));
        button_F1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_F1.setText("Ff");
        button_F1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_F1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_F1MousePressed(evt);
            }
        });

        button_G1.setBackground(new java.awt.Color(255, 153, 255));
        button_G1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_G1.setText("Gg");
        button_G1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_G1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_G1MousePressed(evt);
            }
        });

        button_H1.setBackground(new java.awt.Color(255, 153, 255));
        button_H1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_H1.setText("Hh");
        button_H1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_H1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_H1MousePressed(evt);
            }
        });

        button_I1.setBackground(new java.awt.Color(255, 153, 255));
        button_I1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_I1.setText("Ii");
        button_I1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_I1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_I1MousePressed(evt);
            }
        });

        button_Q1.setBackground(new java.awt.Color(255, 153, 255));
        button_Q1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Q1.setText("Qq");
        button_Q1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Q1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_Q1MousePressed(evt);
            }
        });

        button_P1.setBackground(new java.awt.Color(255, 153, 255));
        button_P1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_P1.setText("Pp");
        button_P1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_P1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_P1MousePressed(evt);
            }
        });

        button_O1.setBackground(new java.awt.Color(255, 153, 255));
        button_O1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_O1.setText("Oo");
        button_O1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_O1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_O1MousePressed(evt);
            }
        });

        button_X1.setBackground(new java.awt.Color(255, 153, 255));
        button_X1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_X1.setText("Xx");
        button_X1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_X1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_X1MousePressed(evt);
            }
        });

        button_Y1.setBackground(new java.awt.Color(255, 153, 255));
        button_Y1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Y1.setText("Yy");
        button_Y1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Y1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_Y1MousePressed(evt);
            }
        });

        button_Z1.setBackground(new java.awt.Color(255, 153, 255));
        button_Z1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Z1.setText("Zz");
        button_Z1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Z1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_Z1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addComponent(button_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_K1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_M1)
                                .addGap(9, 9, 9)
                                .addComponent(button_N1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_Ñ1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_O1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addComponent(button_R1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_S1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_U1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_V1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_W1)
                                .addGap(9, 9, 9)
                                .addComponent(button_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_Z1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel4Layout.createSequentialGroup()
                                .addComponent(button_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_E1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_F1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_G1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_H1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_I1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(218, 218, 218))))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_B1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_D1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_E1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_F1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_G1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_H1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_I1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_J1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_K1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_L1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_M1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_N1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Ñ1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_O1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_P1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Q1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_R1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_S1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_T1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_U1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_V1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_W1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_X1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Y1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Z1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCurves2Layout = new javax.swing.GroupLayout(panelCurves2);
        panelCurves2.setLayout(panelCurves2Layout);
        panelCurves2Layout.setHorizontalGroup(
            panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves2Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panelCurves2Layout.setVerticalGroup(
            panelCurves2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCurves2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(panelCurves2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfabeto/alfa.gif"))); // NOI18N

        panel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel3.setColorPrimario(new java.awt.Color(255, 153, 255));
        panel3.setColorSecundario(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfabeto/abc.gif"))); // NOI18N

        button_A.setBackground(new java.awt.Color(51, 102, 255));
        button_A.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_A.setText("Aa");
        button_A.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_AMousePressed(evt);
            }
        });

        button_J.setBackground(new java.awt.Color(51, 102, 255));
        button_J.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_J.setText("Jj");
        button_J.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_J.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_JMousePressed(evt);
            }
        });

        button_R.setBackground(new java.awt.Color(51, 102, 255));
        button_R.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_R.setText("Rr");
        button_R.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_R.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_RMousePressed(evt);
            }
        });

        button_S.setBackground(new java.awt.Color(51, 102, 255));
        button_S.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_S.setText("Ss");
        button_S.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_SMousePressed(evt);
            }
        });

        button_K.setBackground(new java.awt.Color(51, 102, 255));
        button_K.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_K.setText("Kk");
        button_K.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_KMousePressed(evt);
            }
        });

        button_B.setBackground(new java.awt.Color(51, 102, 255));
        button_B.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_B.setText("Bb");
        button_B.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_BMousePressed(evt);
            }
        });

        button_C.setBackground(new java.awt.Color(51, 102, 255));
        button_C.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_C.setText("Cc");
        button_C.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_CMousePressed(evt);
            }
        });

        button_L.setBackground(new java.awt.Color(51, 102, 255));
        button_L.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_L.setText("Ll");
        button_L.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_LMousePressed(evt);
            }
        });

        button_T.setBackground(new java.awt.Color(51, 102, 255));
        button_T.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_T.setText("Tt");
        button_T.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_TMousePressed(evt);
            }
        });

        button_U.setBackground(new java.awt.Color(51, 102, 255));
        button_U.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_U.setText("Uu");
        button_U.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_UMousePressed(evt);
            }
        });

        button_M.setBackground(new java.awt.Color(51, 102, 255));
        button_M.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_M.setText("Mm");
        button_M.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_MMousePressed(evt);
            }
        });

        button_D.setBackground(new java.awt.Color(51, 102, 255));
        button_D.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_D.setText("Dd");
        button_D.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_DMousePressed(evt);
            }
        });

        button_E.setBackground(new java.awt.Color(51, 102, 255));
        button_E.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_E.setText("Ee");
        button_E.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_EMousePressed(evt);
            }
        });

        button_N.setBackground(new java.awt.Color(51, 102, 255));
        button_N.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_N.setText("Nn");
        button_N.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_NMousePressed(evt);
            }
        });

        button_V.setBackground(new java.awt.Color(51, 102, 255));
        button_V.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_V.setText("Vv");
        button_V.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_V.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_VMousePressed(evt);
            }
        });

        button_W.setBackground(new java.awt.Color(51, 102, 255));
        button_W.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_W.setText("Ww");
        button_W.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_W.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_WMousePressed(evt);
            }
        });

        button_Ñ.setBackground(new java.awt.Color(51, 102, 255));
        button_Ñ.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Ñ.setText("Ññ");
        button_Ñ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Ñ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_ÑMousePressed(evt);
            }
        });

        button_F.setBackground(new java.awt.Color(51, 102, 255));
        button_F.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_F.setText("Ff");
        button_F.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_FMousePressed(evt);
            }
        });

        button_G.setBackground(new java.awt.Color(51, 102, 255));
        button_G.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_G.setText("Gg");
        button_G.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_GMousePressed(evt);
            }
        });

        button_O.setBackground(new java.awt.Color(51, 102, 255));
        button_O.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_O.setText("Oo");
        button_O.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_OMousePressed(evt);
            }
        });

        button_X.setBackground(new java.awt.Color(51, 102, 255));
        button_X.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_X.setText("Xx");
        button_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_XMousePressed(evt);
            }
        });

        button_Y.setBackground(new java.awt.Color(51, 102, 255));
        button_Y.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Y.setText("Yy");
        button_Y.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_YMousePressed(evt);
            }
        });

        button_P.setBackground(new java.awt.Color(51, 102, 255));
        button_P.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_P.setText("Pp");
        button_P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_PMousePressed(evt);
            }
        });

        button_H.setBackground(new java.awt.Color(51, 102, 255));
        button_H.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_H.setText("Hh");
        button_H.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_HMousePressed(evt);
            }
        });

        button_I.setBackground(new java.awt.Color(51, 102, 255));
        button_I.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_I.setText("Ii");
        button_I.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_IMousePressed(evt);
            }
        });

        button_Q.setBackground(new java.awt.Color(51, 102, 255));
        button_Q.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Q.setText("Qq");
        button_Q.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_QMousePressed(evt);
            }
        });

        button_Z.setBackground(new java.awt.Color(51, 102, 255));
        button_Z.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_Z.setText("Zz");
        button_Z.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button_ZMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(button_J, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_K, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_L, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_M)
                        .addGap(9, 9, 9)
                        .addComponent(button_N, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_Ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_O, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_P, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(button_R, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_S, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_T, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_U, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_V, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_W)
                        .addGap(9, 9, 9)
                        .addComponent(button_X, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(button_A, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(button_B, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panel3Layout.createSequentialGroup()
                                .addComponent(button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_D, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_E, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_F, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_G, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_H, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(button_I, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_A, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_B, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_C, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_D, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_E, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_F, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_G, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_H, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_I, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_J, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_K, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_L, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_M, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_N, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Ñ, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_O, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_P, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Q, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_R, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_S, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_T, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_U, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_V, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_W, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_X, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Y, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Z, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/logoM.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelCurves1Layout = new javax.swing.GroupLayout(panelCurves1);
        panelCurves1.setLayout(panelCurves1Layout);
        panelCurves1Layout.setHorizontalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCurves1Layout.createSequentialGroup()
                        .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCurves1Layout.setVerticalGroup(
            panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCurves1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCurves1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCurves1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panelCurves1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfabeto/inicio.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gato/imagenes/inicio2.png"))); // NOI18N
        cerrar.setText("Menú Principal");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jMenu1.add(cerrar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_EMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_EMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/e.wav"));
        audio.play();
    }//GEN-LAST:event_button_EMousePressed

    private void button_AMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_AMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/a.wav"));
        audio.play();
    }//GEN-LAST:event_button_AMousePressed

    private void button_BMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_BMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/b.wav"));
        audio.play();
    }//GEN-LAST:event_button_BMousePressed

    private void button_CMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_CMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/c.wav"));
        audio.play();
    }//GEN-LAST:event_button_CMousePressed

    private void button_DMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_DMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/d.wav"));
        audio.play();
    }//GEN-LAST:event_button_DMousePressed

    private void button_FMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_FMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/f.wav"));
        audio.play();
    }//GEN-LAST:event_button_FMousePressed

    private void button_GMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_GMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/g.wav"));
        audio.play();
    }//GEN-LAST:event_button_GMousePressed

    private void button_HMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_HMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/h.wav"));
        audio.play();
    }//GEN-LAST:event_button_HMousePressed

    private void button_IMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_IMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/i.wav"));
        audio.play();
    }//GEN-LAST:event_button_IMousePressed

    private void button_JMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_JMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/j.wav"));
        audio.play();
    }//GEN-LAST:event_button_JMousePressed

    private void button_KMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_KMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/k.wav"));
        audio.play();
    }//GEN-LAST:event_button_KMousePressed

    private void button_LMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_LMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/l.wav"));
        audio.play();
    }//GEN-LAST:event_button_LMousePressed

    private void button_MMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_MMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/m.wav"));
        audio.play();
    }//GEN-LAST:event_button_MMousePressed

    private void button_NMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_NMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/n.wav"));
        audio.play();
    }//GEN-LAST:event_button_NMousePressed

    private void button_ÑMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ÑMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/ñ.wav"));
        audio.play();
    }//GEN-LAST:event_button_ÑMousePressed

    private void button_OMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_OMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/o.wav"));
        audio.play();
    }//GEN-LAST:event_button_OMousePressed

    private void button_PMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_PMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/p.wav"));
        audio.play();
    }//GEN-LAST:event_button_PMousePressed

    private void button_QMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_QMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/q.wav"));
        audio.play();
    }//GEN-LAST:event_button_QMousePressed

    private void button_RMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_RMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/r.wav"));
        audio.play();
    }//GEN-LAST:event_button_RMousePressed

    private void button_SMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/s.wav"));
        audio.play();
    }//GEN-LAST:event_button_SMousePressed

    private void button_TMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_TMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/t.wav"));
        audio.play();
    }//GEN-LAST:event_button_TMousePressed

    private void button_UMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_UMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/u.wav"));
        audio.play();
    }//GEN-LAST:event_button_UMousePressed

    private void button_VMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_VMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/v.wav"));
        audio.play();
    }//GEN-LAST:event_button_VMousePressed

    private void button_WMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_WMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/w.wav"));
        audio.play();
    }//GEN-LAST:event_button_WMousePressed

    private void button_XMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_XMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/x.wav"));
        audio.play();
    }//GEN-LAST:event_button_XMousePressed

    private void button_YMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_YMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/y.wav"));
        audio.play();
    }//GEN-LAST:event_button_YMousePressed

    private void button_ZMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_ZMousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/abc/z.wav"));
        audio.play();
    }//GEN-LAST:event_button_ZMousePressed

    private void button_E1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_E1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/elefante.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "E L E F A N T E", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/E.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_E1MousePressed

    private void button_A1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_A1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/arbol.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "Á R B O L", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/a.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_A1MousePressed

    private void button_B1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_B1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/baño.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "B A Ñ O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/b.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_B1MousePressed

    private void button_C1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_C1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/corazon.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "C O R A Z Ó N", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/c.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_C1MousePressed

    private void button_D1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_D1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/dedo.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "D E D O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/D.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_D1MousePressed

    private void button_F1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_F1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/flauta.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "F L A U T A", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/F.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_F1MousePressed

    private void button_G1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_G1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/gato.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "G A T O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/G.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_G1MousePressed

    private void button_H1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_H1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/hielo.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "H I E L O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/H.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_H1MousePressed

    private void button_I1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_I1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/iguana.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "I G U A N A", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/I.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_I1MousePressed

    private void button_J1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_J1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/javon.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "J A V Ó N", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/J.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_J1MousePressed

    private void button_K1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_K1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/kiosco.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "K I O S C O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/K.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_K1MousePressed

    private void button_L1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_L1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/lapiz.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "L Á P I Z", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/L.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_L1MousePressed

    private void button_M1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_M1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/mono.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "M O N O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/M.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_M1MousePressed

    private void button_N1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_N1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/niño.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "N I Ñ O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/N.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_N1MousePressed

    private void button_Ñ1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_Ñ1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/uña.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "U Ñ A", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/Ñ.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_Ñ1MousePressed

    private void button_O1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_O1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/otoño.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "O T O Ñ O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/O.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_O1MousePressed

    private void button_P1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_P1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/puerta.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "P U E R T A", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/P.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_P1MousePressed

    private void button_Q1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_Q1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/queso.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "Q U E S O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/Q.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_Q1MousePressed

    private void button_R1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_R1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/rio.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "R Í O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/R.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_R1MousePressed

    private void button_S1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_S1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/sol.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "S O L", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/S.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_S1MousePressed

    private void button_T1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_T1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/tren.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "T R E N", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/T.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_T1MousePressed

    private void button_U1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_U1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/uva.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "U V A", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/U.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_U1MousePressed

    private void button_V1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_V1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/ventana.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "V E N T A N A", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/V.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_V1MousePressed

    private void button_W1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_W1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/winsurf.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "W I N D S U R F", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/W.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_W1MousePressed

    private void button_X1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_X1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/xilofono.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "X I L Ó F O N O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/X.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_X1MousePressed

    private void button_Y1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_Y1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/yema.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "Y E M A", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/Y.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_Y1MousePressed

    private void button_Z1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_Z1MousePressed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/palabras/zapato.wav"));
        audio.play();
        JOptionPane.showMessageDialog(null, "Z A P A T O", "Mensaje", 0, new javax.swing.ImageIcon(getClass().getResource("/alfabeto/imapalabra/Z.png")));
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }//GEN-LAST:event_button_Z1MousePressed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/gato/2.mp3"));
        inicio.play();
        int seleccion = JOptionPane.showConfirmDialog(null, "¿Regresar al menú principal?",
                "Alfabeto",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                new javax.swing.ImageIcon(getClass().getResource("/gato/imagenes/inicio1.png")));
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/gato/2.mp3"));
        inicio.play();

        if (seleccion == 0) {
            this.dispose();
            Ventana v = new Ventana();
            v.setVisible(true);
        }
    }//GEN-LAST:event_cerrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        close();
    }//GEN-LAST:event_formWindowClosing
    private void close() {
        if (JOptionPane.showConfirmDialog(rootPane, "¿Salir de la aplicación?",
                "Alfabeto", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE) == JOptionPane.YES_OPTION) {
            audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
            audio1.play();
            System.exit(0);
        } else {
            audio1 = java.applet.Applet.newAudioClip(getClass().getResource("/ahorcado/tonos/2.mp3"));
            audio1.play();
            setDefaultCloseOperation(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alfabeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alfabeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_A;
    private javax.swing.JButton button_A1;
    private javax.swing.JButton button_B;
    private javax.swing.JButton button_B1;
    private javax.swing.JButton button_C;
    private javax.swing.JButton button_C1;
    private javax.swing.JButton button_D;
    private javax.swing.JButton button_D1;
    private javax.swing.JButton button_E;
    private javax.swing.JButton button_E1;
    private javax.swing.JButton button_F;
    private javax.swing.JButton button_F1;
    private javax.swing.JButton button_G;
    private javax.swing.JButton button_G1;
    private javax.swing.JButton button_H;
    private javax.swing.JButton button_H1;
    private javax.swing.JButton button_I;
    private javax.swing.JButton button_I1;
    private javax.swing.JButton button_J;
    private javax.swing.JButton button_J1;
    private javax.swing.JButton button_K;
    private javax.swing.JButton button_K1;
    private javax.swing.JButton button_L;
    private javax.swing.JButton button_L1;
    private javax.swing.JButton button_M;
    private javax.swing.JButton button_M1;
    private javax.swing.JButton button_N;
    private javax.swing.JButton button_N1;
    private javax.swing.JButton button_O;
    private javax.swing.JButton button_O1;
    private javax.swing.JButton button_P;
    private javax.swing.JButton button_P1;
    private javax.swing.JButton button_Q;
    private javax.swing.JButton button_Q1;
    private javax.swing.JButton button_R;
    private javax.swing.JButton button_R1;
    private javax.swing.JButton button_S;
    private javax.swing.JButton button_S1;
    private javax.swing.JButton button_T;
    private javax.swing.JButton button_T1;
    private javax.swing.JButton button_U;
    private javax.swing.JButton button_U1;
    private javax.swing.JButton button_V;
    private javax.swing.JButton button_V1;
    private javax.swing.JButton button_W;
    private javax.swing.JButton button_W1;
    private javax.swing.JButton button_X;
    private javax.swing.JButton button_X1;
    private javax.swing.JButton button_Y;
    private javax.swing.JButton button_Y1;
    private javax.swing.JButton button_Z;
    private javax.swing.JButton button_Z1;
    private javax.swing.JButton button_Ñ;
    private javax.swing.JButton button_Ñ1;
    private javax.swing.JMenuItem cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables

}
