/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matematicas;

import static java.applet.Applet.newAudioClip;
import java.applet.AudioClip;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryam
 */
public class Tablas extends javax.swing.JFrame {

    AudioClip audio, clic, inicio;
    int pres = 0;

    /**
     * Creates new form Tablas
     */
    public Tablas() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/principal/logoM.png")).getImage());
        setSize(880, 551);
        setLocationRelativeTo(null);
        setResizable(false);
        ant.setEnabled(false);
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        _1x9 = new javax.swing.JButton();
        _1x8 = new javax.swing.JButton();
        _1x7 = new javax.swing.JButton();
        _1x6 = new javax.swing.JButton();
        _1x5 = new javax.swing.JButton();
        _1x4 = new javax.swing.JButton();
        _1x3 = new javax.swing.JButton();
        _1x2 = new javax.swing.JButton();
        _1x1 = new javax.swing.JButton();
        _1x10 = new javax.swing.JButton();
        luno = new javax.swing.JLabel();
        ldos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        _2x9 = new javax.swing.JButton();
        _2x8 = new javax.swing.JButton();
        _2x7 = new javax.swing.JButton();
        _2x6 = new javax.swing.JButton();
        _2x5 = new javax.swing.JButton();
        _2x4 = new javax.swing.JButton();
        _2x3 = new javax.swing.JButton();
        _2x2 = new javax.swing.JButton();
        _2x1 = new javax.swing.JButton();
        _2x10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        _4x9 = new javax.swing.JButton();
        _4x8 = new javax.swing.JButton();
        _4x7 = new javax.swing.JButton();
        _4x6 = new javax.swing.JButton();
        _4x5 = new javax.swing.JButton();
        _4x4 = new javax.swing.JButton();
        _4x3 = new javax.swing.JButton();
        _4x2 = new javax.swing.JButton();
        _4x1 = new javax.swing.JButton();
        _4x10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        _3x9 = new javax.swing.JButton();
        _3x8 = new javax.swing.JButton();
        _3x7 = new javax.swing.JButton();
        _3x6 = new javax.swing.JButton();
        _3x5 = new javax.swing.JButton();
        _3x4 = new javax.swing.JButton();
        _3x3 = new javax.swing.JButton();
        _3x2 = new javax.swing.JButton();
        _3x1 = new javax.swing.JButton();
        _3x10 = new javax.swing.JButton();
        ltres = new javax.swing.JLabel();
        lcuatro = new javax.swing.JLabel();
        lcinco = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        _5x9 = new javax.swing.JButton();
        _5x8 = new javax.swing.JButton();
        _5x7 = new javax.swing.JButton();
        _5x6 = new javax.swing.JButton();
        _5x5 = new javax.swing.JButton();
        _5x4 = new javax.swing.JButton();
        _5x3 = new javax.swing.JButton();
        _5x2 = new javax.swing.JButton();
        _5x1 = new javax.swing.JButton();
        _5x10 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        ant = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        regresars = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matematicas/fondoMate.png"))); // NOI18N
        jcMousePanel1.setIconLogo(new javax.swing.ImageIcon(getClass().getResource("/principal/logoM.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("¡¡¡ APRENDIENDO LAS TABLAS DE MULTIPLICAR !!!");

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        _1x9.setBackground(new java.awt.Color(51, 204, 255));
        _1x9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x9.setText("1 x 9 = 9");
        _1x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x9ActionPerformed(evt);
            }
        });

        _1x8.setBackground(new java.awt.Color(51, 204, 255));
        _1x8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x8.setText("1 x 8 = 8");
        _1x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x8ActionPerformed(evt);
            }
        });

        _1x7.setBackground(new java.awt.Color(51, 204, 255));
        _1x7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x7.setText("1 x 7 = 7");
        _1x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x7ActionPerformed(evt);
            }
        });

        _1x6.setBackground(new java.awt.Color(51, 204, 255));
        _1x6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x6.setText("1 x 6 = 6");
        _1x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x6ActionPerformed(evt);
            }
        });

        _1x5.setBackground(new java.awt.Color(51, 204, 255));
        _1x5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x5.setText("1 x 5 = 5");
        _1x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x5ActionPerformed(evt);
            }
        });

        _1x4.setBackground(new java.awt.Color(51, 204, 255));
        _1x4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x4.setText("1 x 4 = 4");
        _1x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x4ActionPerformed(evt);
            }
        });

        _1x3.setBackground(new java.awt.Color(51, 204, 255));
        _1x3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x3.setText("1 x 3 = 3");
        _1x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x3ActionPerformed(evt);
            }
        });

        _1x2.setBackground(new java.awt.Color(51, 204, 255));
        _1x2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x2.setText("1 x 2 = 2");
        _1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x2ActionPerformed(evt);
            }
        });

        _1x1.setBackground(new java.awt.Color(51, 204, 255));
        _1x1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x1.setText("1 x 1 = 1");
        _1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x1ActionPerformed(evt);
            }
        });

        _1x10.setBackground(new java.awt.Color(51, 204, 255));
        _1x10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _1x10.setText("1 x 10 = 10");
        _1x10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _1x10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(_1x8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_1x9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_1x10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_1x1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_1x10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        luno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        luno.setText("Tabla del Uno.");

        ldos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ldos.setText("Tabla del Dos.");

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));

        _2x9.setBackground(new java.awt.Color(153, 255, 153));
        _2x9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x9.setText("2 x 9 = 18");
        _2x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x9ActionPerformed(evt);
            }
        });

        _2x8.setBackground(new java.awt.Color(153, 255, 153));
        _2x8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x8.setText("2 x 8 = 16");
        _2x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x8ActionPerformed(evt);
            }
        });

        _2x7.setBackground(new java.awt.Color(153, 255, 153));
        _2x7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x7.setText("2 x 7 = 14");
        _2x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x7ActionPerformed(evt);
            }
        });

        _2x6.setBackground(new java.awt.Color(153, 255, 153));
        _2x6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x6.setText("2 x 6 = 12");
        _2x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x6ActionPerformed(evt);
            }
        });

        _2x5.setBackground(new java.awt.Color(153, 255, 153));
        _2x5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x5.setText("2 x 5 = 10");
        _2x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x5ActionPerformed(evt);
            }
        });

        _2x4.setBackground(new java.awt.Color(153, 255, 153));
        _2x4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x4.setText("2 x 4 = 8");
        _2x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x4ActionPerformed(evt);
            }
        });

        _2x3.setBackground(new java.awt.Color(153, 255, 153));
        _2x3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x3.setText("2 x 3 = 6");
        _2x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x3ActionPerformed(evt);
            }
        });

        _2x2.setBackground(new java.awt.Color(153, 255, 153));
        _2x2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x2.setText("2 x 2 = 4");
        _2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x2ActionPerformed(evt);
            }
        });

        _2x1.setBackground(new java.awt.Color(153, 255, 153));
        _2x1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x1.setText("2 x 1 = 2");
        _2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x1ActionPerformed(evt);
            }
        });

        _2x10.setBackground(new java.awt.Color(153, 255, 153));
        _2x10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _2x10.setText("2 x 10 = 20");
        _2x10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _2x10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(_2x8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_2x9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_2x10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_2x1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_2x10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        _4x9.setBackground(new java.awt.Color(255, 153, 153));
        _4x9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x9.setText("4 x 9 = 36");
        _4x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x9ActionPerformed(evt);
            }
        });

        _4x8.setBackground(new java.awt.Color(255, 153, 153));
        _4x8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x8.setText("4 x 8 = 32");
        _4x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x8ActionPerformed(evt);
            }
        });

        _4x7.setBackground(new java.awt.Color(255, 153, 153));
        _4x7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x7.setText("4 x 7 = 28");
        _4x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x7ActionPerformed(evt);
            }
        });

        _4x6.setBackground(new java.awt.Color(255, 153, 153));
        _4x6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x6.setText("4 x 6 = 24");
        _4x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x6ActionPerformed(evt);
            }
        });

        _4x5.setBackground(new java.awt.Color(255, 153, 153));
        _4x5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x5.setText("4 x 5 = 20");
        _4x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x5ActionPerformed(evt);
            }
        });

        _4x4.setBackground(new java.awt.Color(255, 153, 153));
        _4x4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x4.setText("4 x 4 = 16");
        _4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x4ActionPerformed(evt);
            }
        });

        _4x3.setBackground(new java.awt.Color(255, 153, 153));
        _4x3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x3.setText("4 x 3 = 14");
        _4x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x3ActionPerformed(evt);
            }
        });

        _4x2.setBackground(new java.awt.Color(255, 153, 153));
        _4x2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x2.setText("4 x 2 = 8");
        _4x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x2ActionPerformed(evt);
            }
        });

        _4x1.setBackground(new java.awt.Color(255, 153, 153));
        _4x1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x1.setText("4 x 1 = 4");
        _4x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x1ActionPerformed(evt);
            }
        });

        _4x10.setBackground(new java.awt.Color(255, 153, 153));
        _4x10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _4x10.setText("4 x 10 = 40");
        _4x10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _4x10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(_4x8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_4x9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_4x10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_4x1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_4x10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 0, 255));

        _3x9.setBackground(new java.awt.Color(255, 204, 255));
        _3x9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x9.setText("3 x 9 = 27");
        _3x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x9ActionPerformed(evt);
            }
        });

        _3x8.setBackground(new java.awt.Color(255, 204, 255));
        _3x8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x8.setText("3 x 8 = 24");
        _3x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x8ActionPerformed(evt);
            }
        });

        _3x7.setBackground(new java.awt.Color(255, 204, 255));
        _3x7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x7.setText("3 x 7 = 21");
        _3x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x7ActionPerformed(evt);
            }
        });

        _3x6.setBackground(new java.awt.Color(255, 204, 255));
        _3x6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x6.setText("3 x 6 = 18");
        _3x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x6ActionPerformed(evt);
            }
        });

        _3x5.setBackground(new java.awt.Color(255, 204, 255));
        _3x5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x5.setText("3 x 5 = 15");
        _3x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x5ActionPerformed(evt);
            }
        });

        _3x4.setBackground(new java.awt.Color(255, 204, 255));
        _3x4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x4.setText("3 x 4 = 12");
        _3x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x4ActionPerformed(evt);
            }
        });

        _3x3.setBackground(new java.awt.Color(255, 204, 255));
        _3x3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x3.setText("3 x 3 = 9");
        _3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x3ActionPerformed(evt);
            }
        });

        _3x2.setBackground(new java.awt.Color(255, 204, 255));
        _3x2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x2.setText("3 x 2 = 6");
        _3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x2ActionPerformed(evt);
            }
        });

        _3x1.setBackground(new java.awt.Color(255, 204, 255));
        _3x1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x1.setText("3 x 1 = 3");
        _3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x1ActionPerformed(evt);
            }
        });

        _3x10.setBackground(new java.awt.Color(255, 204, 255));
        _3x10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _3x10.setText("3 x 10 = 30");
        _3x10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _3x10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(_3x8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(_3x9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(_3x10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_3x1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_3x10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ltres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ltres.setText("Tabla del Tres.");

        lcuatro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lcuatro.setText("Tabla del Cuatro.");

        lcinco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lcinco.setText("Tabla del Cinco.");

        jPanel5.setBackground(new java.awt.Color(255, 255, 51));

        _5x9.setBackground(new java.awt.Color(255, 255, 153));
        _5x9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x9.setText("5 x 9 = 45");
        _5x9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x9ActionPerformed(evt);
            }
        });

        _5x8.setBackground(new java.awt.Color(255, 255, 153));
        _5x8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x8.setText("5 x 8 = 40");
        _5x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x8ActionPerformed(evt);
            }
        });

        _5x7.setBackground(new java.awt.Color(255, 255, 153));
        _5x7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x7.setText("5 x 7 = 5");
        _5x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x7ActionPerformed(evt);
            }
        });

        _5x6.setBackground(new java.awt.Color(255, 255, 153));
        _5x6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x6.setText("5 x 6 = 30");
        _5x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x6ActionPerformed(evt);
            }
        });

        _5x5.setBackground(new java.awt.Color(255, 255, 153));
        _5x5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x5.setText("5 x 5 = 25");
        _5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x5ActionPerformed(evt);
            }
        });

        _5x4.setBackground(new java.awt.Color(255, 255, 153));
        _5x4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x4.setText("5 x 4 = 20");
        _5x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x4ActionPerformed(evt);
            }
        });

        _5x3.setBackground(new java.awt.Color(255, 255, 153));
        _5x3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x3.setText("5 x 3 = 15");
        _5x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x3ActionPerformed(evt);
            }
        });

        _5x2.setBackground(new java.awt.Color(255, 255, 153));
        _5x2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x2.setText("5 x 2 = 10");
        _5x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x2ActionPerformed(evt);
            }
        });

        _5x1.setBackground(new java.awt.Color(255, 255, 153));
        _5x1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x1.setText("5 x 1 = 5");
        _5x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x1ActionPerformed(evt);
            }
        });

        _5x10.setBackground(new java.awt.Color(255, 255, 153));
        _5x10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        _5x10.setText("5 x 10 = 50");
        _5x10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _5x10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_5x10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(_5x8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_5x9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_5x1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_5x10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        next.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matematicas/numeros/next.png"))); // NOI18N
        next.setToolTipText("Siguiente");
        next.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        ant.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/matematicas/numeros/anterior.png"))); // NOI18N
        ant.setToolTipText("Anterior");
        ant.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ant, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(luno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ldos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcuatro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lcinco)
                            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ldos)
                            .addComponent(luno)
                            .addComponent(ltres)
                            .addComponent(lcuatro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jcMousePanel1Layout.createSequentialGroup()
                        .addComponent(lcinco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alfabeto/inicio.png"))); // NOI18N
        jMenu1.setText("Inicio");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        regresars.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        regresars.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        regresars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pares/pares/pick/regresar.png"))); // NOI18N
        regresars.setText("Regresar al menú");
        regresars.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarsActionPerformed(evt);
            }
        });
        jMenu1.add(regresars);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        pres = 1;
        if (pres == 1) {
            luno.setText("Tabla del Seis.");            
            _1x1.setText("6 x 1 = 6");
            _1x2.setText("6 x 2 = 12");
            _1x3.setText("6 x 3 = 18");
            _1x4.setText("6 x 4 = 24");
            _1x5.setText("6 x 5 = 30");
            _1x6.setText("6 x 6 = 36");
            _1x7.setText("6 x 7 = 42");
            _1x8.setText("6 x 8 = 48");
            _1x9.setText("6 x 9 = 54");
            _1x10.setText("6 x 10 = 60");
            
            ldos.setText("Tabla del Siete.");
            _2x1.setText("7 x 1 = 7");
            _2x2.setText("7 x 2 = 14");
            _2x3.setText("7 x 3 = 21");
            _2x4.setText("7 x 4 = 28");
            _2x5.setText("7 x 5 = 35");
            _2x6.setText("7 x 6 = 42");
            _2x7.setText("7 x 7 = 49");
            _2x8.setText("7 x 8 = 56");
            _2x9.setText("7 x 9 = 63");
            _2x10.setText("7 x 10 = 70");
            
            ltres.setText("Tabla del Ocho.");
            _3x1.setText("8 x 1 = 8");
            _3x2.setText("8 x 2 = 16");
            _3x3.setText("8 x 3 = 24");
            _3x4.setText("8 x 4 = 32");
            _3x5.setText("8 x 5 = 40");
            _3x6.setText("8 x 6 = 48");
            _3x7.setText("8 x 7 = 56");
            _3x8.setText("8 x 8 = 64");
            _3x9.setText("8 x 9 = 72");
            _3x10.setText("8 x 10 = 80");
            
            lcuatro.setText("Tabla del Nueve.");
            _4x1.setText("9 x 1 = 9");
            _4x2.setText("9 x 2 = 18");
            _4x3.setText("9 x 3 = 27");
            _4x4.setText("9 x 4 = 36");
            _4x5.setText("9 x 5 = 45");
            _4x6.setText("9 x 6 = 54");
            _4x7.setText("9 x 7 = 63");
            _4x8.setText("9 x 8 = 72");
            _4x9.setText("9 x 9 = 81");
            _4x10.setText("9 x 10 = 90");
            
            lcinco.setText("Tabla del Diez.");
            _5x1.setText("10 x 1 = 10");
            _5x2.setText("10 x 2 = 20");
            _5x3.setText("10 x 3 = 30");
            _5x4.setText("10 x 4 = 40");
            _5x5.setText("10 x 5 = 50");
            _5x6.setText("10 x 6 = 60");
            _5x7.setText("10 x 7 = 70");
            _5x8.setText("10 x 8 = 80");
            _5x9.setText("10 x 9 = 90");
            _5x10.setText("10 x 10 = 100");
            
            ant.setEnabled(true);
            next.setEnabled(false);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void _1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x1ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/61.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/11.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x1ActionPerformed

    private void _1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x2ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/62.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/12.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x2ActionPerformed

    private void _1x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x3ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/63.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/13.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x3ActionPerformed

    private void _1x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x4ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/64.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/14.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x4ActionPerformed

    private void _1x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x5ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/65.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/15.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x5ActionPerformed

    private void _1x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x6ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/66.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/16.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x6ActionPerformed

    private void _1x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x7ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/67.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/17.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x7ActionPerformed

    private void _1x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x8ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/68.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/18.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x8ActionPerformed

    private void _1x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x9ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/69.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/19.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x9ActionPerformed

    private void _1x10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__1x10ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/seis/610.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/uno/110.wav"));
            audio.play();
        }
    }//GEN-LAST:event__1x10ActionPerformed

    private void _2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x1ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/71.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/21.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x1ActionPerformed

    private void _2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x2ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/72.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/22.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x2ActionPerformed

    private void _2x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x3ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/73.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/23.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x3ActionPerformed

    private void _2x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x4ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/74.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/24.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x4ActionPerformed

    private void _2x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x5ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/75.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/25.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x5ActionPerformed

    private void _2x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x6ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/76.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/26.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x6ActionPerformed

    private void _2x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x7ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/77.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/27.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x7ActionPerformed

    private void _2x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x8ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/78.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/28.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x8ActionPerformed

    private void _2x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x9ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/79.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/29.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x9ActionPerformed

    private void _2x10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__2x10ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/siete/710.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/dos/210.wav"));
            audio.play();
        }
    }//GEN-LAST:event__2x10ActionPerformed

    private void _3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x1ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/81.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/31.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x1ActionPerformed

    private void _3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x2ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/82.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/32.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x2ActionPerformed

    private void _3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x3ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/83.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/33.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x3ActionPerformed

    private void _3x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x4ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/84.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/34.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x4ActionPerformed

    private void _3x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x5ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/85.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/35.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x5ActionPerformed

    private void _3x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x6ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/86.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/36.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x6ActionPerformed

    private void _3x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x7ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/87.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/37.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x7ActionPerformed

    private void _3x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x8ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/88.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/38.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x8ActionPerformed

    private void _3x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x9ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/89.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/39.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x9ActionPerformed

    private void _3x10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__3x10ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/ocho/810.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/tres/310.wav"));
            audio.play();
        }
    }//GEN-LAST:event__3x10ActionPerformed

    private void _4x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x1ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/91.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/41.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x1ActionPerformed

    private void _4x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x2ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/92.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/42.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x2ActionPerformed

    private void _4x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x3ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/93.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/43.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x3ActionPerformed

    private void _4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x4ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/94.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/44.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x4ActionPerformed

    private void _4x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x5ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/95.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/45.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x5ActionPerformed

    private void _4x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x6ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/96.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/46.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x6ActionPerformed

    private void _4x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x7ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/97.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/47.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x7ActionPerformed

    private void _4x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x8ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/98.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/48.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x8ActionPerformed

    private void _4x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x9ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/99.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/49.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x9ActionPerformed

    private void _4x10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__4x10ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/nueve/910.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cuatro/410.wav"));
            audio.play();
        }
    }//GEN-LAST:event__4x10ActionPerformed

    private void _5x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x1ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_1.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/51.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x1ActionPerformed

    private void _5x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x2ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_2.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/52.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x2ActionPerformed

    private void _5x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x3ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_3.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/53.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x3ActionPerformed

    private void _5x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x4ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_4.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/54.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x4ActionPerformed

    private void _5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x5ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_5.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/55.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x5ActionPerformed

    private void _5x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x6ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_6.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/56.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x6ActionPerformed

    private void _5x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x7ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
       if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_7.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/57.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x7ActionPerformed

    private void _5x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x8ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_8.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/58.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x8ActionPerformed

    private void _5x9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x9ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_9.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/59.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x9ActionPerformed

    private void _5x10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__5x10ActionPerformed
        audio.stop();
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        if (pres == 1) {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/diez/10_10.wav"));
            audio.play();
        } else {
            audio = newAudioClip(getClass().getResource("/matematicas/tablas/cinco/510.wav"));
            audio.play();
        }
    }//GEN-LAST:event__5x10ActionPerformed

    private void antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antActionPerformed
        audio = java.applet.Applet.newAudioClip(getClass().getResource("/alfabeto/2.mp3"));
        audio.play();
        pres = 0;
        if (pres == 0) {
            luno.setText("Tabla del Uno.");            
            _1x1.setText("1 x 1 = 1");
            _1x2.setText("1 x 2 = 2");
            _1x3.setText("1 x 3 = 3");
            _1x4.setText("1 x 4 = 4");
            _1x5.setText("1 x 5 = 5");
            _1x6.setText("1 x 6 = 6");
            _1x7.setText("1 x 7 = 7");
            _1x8.setText("1 x 8 = 8");
            _1x9.setText("1 x 9 = 9");
            _1x10.setText("1 x 10 = 10");
            
            ldos.setText("Tabla del Dos.");
            _2x1.setText("2 x 1 = 2");
            _2x2.setText("2 x 2 = 4");
            _2x3.setText("2 x 3 = 6");
            _2x4.setText("2 x 4 = 8");
            _2x5.setText("2 x 5 = 10");
            _2x6.setText("2 x 6 = 12");
            _2x7.setText("2 x 7 = 14");
            _2x8.setText("2 x 8 = 16");
            _2x9.setText("2 x 9 = 18");
            _2x10.setText("2 x 10 = 20");
            
            ltres.setText("Tabla del Tres.");
            _3x1.setText("3 x 1 = 3");
            _3x2.setText("3 x 2 = 6");
            _3x3.setText("3 x 3 = 9");
            _3x4.setText("3 x 4 = 12");
            _3x5.setText("3 x 5 = 15");
            _3x6.setText("3 x 6 = 18");
            _3x7.setText("3 x 7 = 21");
            _3x8.setText("3 x 8 = 24");
            _3x9.setText("3 x 9 = 27");
            _3x10.setText("3 x 10 = 30");
            
            lcuatro.setText("Tabla del Cuatro.");
            _4x1.setText("4 x 1 = 4");
            _4x2.setText("4 x 2 = 8");
            _4x3.setText("4 x 3 = 12");
            _4x4.setText("4 x 4 = 16");
            _4x5.setText("4 x 5 = 20");
            _4x6.setText("4 x 6 = 24");
            _4x7.setText("4 x 7 = 28");
            _4x8.setText("4 x 8 = 32");
            _4x9.setText("4 x 9 = 36");
            _4x10.setText("4 x 10 = 40");
            
            lcinco.setText("Tabla del Cinco.");
            _5x1.setText("5 x 1 = 5");
            _5x2.setText("5 x 2 = 10");
            _5x3.setText("5 x 3 = 15");
            _5x4.setText("5 x 4 = 20");
            _5x5.setText("5 x 5 = 25");
            _5x6.setText("5 x 6 = 30");
            _5x7.setText("5 x 7 = 35");
            _5x8.setText("5 x 8 = 40");
            _5x9.setText("5 x 9 = 45");
            _5x10.setText("5 x 10 = 50");
            
            ant.setEnabled(false);
            next.setEnabled(true);
        }
    }//GEN-LAST:event_antActionPerformed

    private void regresarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarsActionPerformed
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/pares/tonos/2.mp3"));
        inicio.play();
        int seleccion = JOptionPane.showConfirmDialog(null, "¿Regresar al menú?", "Matemáticas",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
            new ImageIcon(getClass().getResource("/pares/pares/pick/regreG.png")));
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/pares/tonos/2.mp3"));
        inicio.play();
        if (seleccion == 0) {
            this.dispose();
            new inicioMat().setVisible(true);
        }
    }//GEN-LAST:event_regresarsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        inicio = java.applet.Applet.newAudioClip(getClass().getResource("/gato/2.mp3"));
        inicio.play();
        if (JOptionPane.showConfirmDialog(rootPane, "¿Salir de la aplicación?",
                "Matemáticas", JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE) == JOptionPane.YES_OPTION) {
            inicio = java.applet.Applet.newAudioClip(getClass().getResource("/gato/2.mp3"));
            inicio.play();
            System.exit(0);
        } else {
            inicio = java.applet.Applet.newAudioClip(getClass().getResource("/gato/2.mp3"));
            inicio.play();
            setDefaultCloseOperation(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _1x1;
    private javax.swing.JButton _1x10;
    private javax.swing.JButton _1x2;
    private javax.swing.JButton _1x3;
    private javax.swing.JButton _1x4;
    private javax.swing.JButton _1x5;
    private javax.swing.JButton _1x6;
    private javax.swing.JButton _1x7;
    private javax.swing.JButton _1x8;
    private javax.swing.JButton _1x9;
    private javax.swing.JButton _2x1;
    private javax.swing.JButton _2x10;
    private javax.swing.JButton _2x2;
    private javax.swing.JButton _2x3;
    private javax.swing.JButton _2x4;
    private javax.swing.JButton _2x5;
    private javax.swing.JButton _2x6;
    private javax.swing.JButton _2x7;
    private javax.swing.JButton _2x8;
    private javax.swing.JButton _2x9;
    private javax.swing.JButton _3x1;
    private javax.swing.JButton _3x10;
    private javax.swing.JButton _3x2;
    private javax.swing.JButton _3x3;
    private javax.swing.JButton _3x4;
    private javax.swing.JButton _3x5;
    private javax.swing.JButton _3x6;
    private javax.swing.JButton _3x7;
    private javax.swing.JButton _3x8;
    private javax.swing.JButton _3x9;
    private javax.swing.JButton _4x1;
    private javax.swing.JButton _4x10;
    private javax.swing.JButton _4x2;
    private javax.swing.JButton _4x3;
    private javax.swing.JButton _4x4;
    private javax.swing.JButton _4x5;
    private javax.swing.JButton _4x6;
    private javax.swing.JButton _4x7;
    private javax.swing.JButton _4x8;
    private javax.swing.JButton _4x9;
    private javax.swing.JButton _5x1;
    private javax.swing.JButton _5x10;
    private javax.swing.JButton _5x2;
    private javax.swing.JButton _5x3;
    private javax.swing.JButton _5x4;
    private javax.swing.JButton _5x5;
    private javax.swing.JButton _5x6;
    private javax.swing.JButton _5x7;
    private javax.swing.JButton _5x8;
    private javax.swing.JButton _5x9;
    private javax.swing.JButton ant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JLabel lcinco;
    private javax.swing.JLabel lcuatro;
    private javax.swing.JLabel ldos;
    private javax.swing.JLabel ltres;
    private javax.swing.JLabel luno;
    private javax.swing.JButton next;
    private javax.swing.JMenuItem regresars;
    // End of variables declaration//GEN-END:variables
}
